name: run-tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        php: [8.1, 8.2]
        dependency-version: [prefer-lowest, prefer-stable]

    name: P${{ matrix.php }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      - name: Install PHP 7 dependencies
        run: composer update --${{ matrix.dependency-version }} --no-interaction --no-progress
        if: "matrix.php < 8"

      - name: Install PHP 8 dependencies
        run: composer update --${{ matrix.dependency-version }} --ignore-platform-req=php --no-interaction --no-progress
        if: "matrix.php >= 8"

      - name: Execute tests
        run: vendor/bin/pest
